apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-redis-cluster
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
data:
  redis.conf: {{ .Values.redisCluster.redisConf | toYaml | indent 1 }}
  update-node.sh: {{ .Values.redisCluster.updateNodeSh | toYaml | indent 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-redis-cluster
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redisCluster.type }}
  selector:
    app: redis-cluster
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.redisCluster.ports | toYaml | nindent 2 -}}