# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  repo: lwplapbs
  imge: go-redis-app

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest


    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: lwplapbs/go-redis-app
          
      - name: echo step variables
        run: echo "${{ github.run_id }}"
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: zubinrich2/go-redis-app:${{ github.run_id }}

      - name: update kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name eks-cluster
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: Switch to staging cluster
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            manifests/redis-master.yml
            manifests/redis-configmap.yml
            manifests/go-redis-svc.yml
            manifests/go-redis-app.yml
          replacement-method: defined
        env:
          IMAGE_TAG: ${{ github.run_id }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'






