apiVersion: v1
kind: Service
metadata:
  name: frontend-nginxapp-loadbalcner-service
  labels: 
    app: frontend-nginxapp
    tier: frontend     
spec:
  type: LoadBalancer 
  selector:
    app: frontend-nginxapp
  ports: 
    - name: http
      port: 80
      targetPort: 8080
