# This is a workflow to provision three tier architecture

name: build golden image for web server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
        - web-image/*
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "provision"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
      PKR_VAR_region: us-east-1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup packer
        uses: hashicorp/setup-packer@main

      # initialize packer
      - name: packer initialization
        run: packer init web_image
      
      # terraform format and validation
      - name: packer validation
        run: |
          packer fmt web_image
          packer validate web_image
            
      # build golden image
      - name: packer build
        run: packer build web_image
        
