# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest


    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: zubinrich2/go-redis-app
          
      - name: echo step variables
        run: echo "${{ github.run_id }}"
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./go-redis-app
          push: true
          tags: zubinrich2/go-redis-app:${{ github.run_id }}

      - name: update kubeconfig
        run: |
            export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
            $(aws sts assume-role \
            --role-arn arn:aws:iam::869510502397:role/batch_july_sts_assume_role \
            --role-session-name updateconfig \
            --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
            --output text))
            aws eks --region us-east-2 update-kubeconfig --name hr-digital-prod --role-arn arn:aws:iam::869510502397:role/batch_july_sts_assume_role
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'

      - name: Switch to staging cluster
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            ./go-redis-app/manifests/redis-master.yml
            ./go-redis-app/manifests/redis-configmap.yml
            ./go-redis-app/manifests/go-redis-svc.yml
            ./go-redis-app/manifests/go-redis-app.yml
          replacement-method: defined
        env:
          IMAGE_TAG: ${{ github.run_id }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'