# This is a workflow to provision three tier architecture

name: package app war file

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "provision"
  build:
    # The type of runner that the job will run on
    name: build
    runs-on: ubuntu-latest
    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
    #   PKR_VAR_region: us-east-1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
            repository: 'Gauravlwplabs/java-db-Login'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: '8'
            distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package
    
      - name: create directory for artifact
        run: mkdir package & cp target/*.war package/application.war

      - uses: actions/upload-artifact@v3
        with:
            name: my-artifact
            path: package

  deploy:
    name: deploy-to-s3
    runs-on: ubuntu-latest
    needs: build
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
        AWS_REGION: "us-east-1"
    steps:
        - name: download package
          uses: actions/download-artifact@v3
          with:
            name: my-artifact
            path: package
        
        - name: deploy package
          run: aws s3 cp package/*.war s3://artifactbucketsept23

